name: Electron CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'screen-recorder/**'
      - '.github/workflows/electron.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd screen-recorder
        npm ci
        npm run make
