name: Electron CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'screen-recorder/**'
      - '.github/workflows/electron.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
    - uses: knicknic/os-specific-run@main
      with:
        macos: |
          cd screen-recorder
          sudo npm i -g npm
          npm ci
          npm run make
        linux: |
          cd screen-recorder
          sudo npm i -g npm
          npm ci
          npm run make
        windows: |
          cd screen-recorder
          npm i -g npm
          npm ci
          npm run make
